version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: firefly-iii-importer_importer_1
      APP_PORT: 8080

  importer:
    image: fireflyiii/data-importer:version-1.5.4@sha256:a52d009eab9f8011bca1c8c479f34a4eb2bb9305029d309c48ecb041412a03e2
    restart: on-failure
    environment:
      # firefly-iii container:
      - FIREFLY_III_URL=http://firefly-iii_server_1:8080
      - VANITY_URL=http://${DEVICE_DOMAIN_NAME}:30009