version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: element_web_1
      APP_PORT: 80

  web:
    image: vectorim/element-web:v1.11.75@sha256:70b807069344a06797bc340f748f5850e88a3bd670b374e03a9f84d77322b285
    # NGINX parent container requires root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m