version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: freshrss_server_1
      APP_PORT: 80
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/freshrss:1.24.2@sha256:c25bdcb475160fb9ac8e0dfd2c44d0c865663a8cc80c9698aa3f02a2f0fe2205
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config