version: "3.7"

services:
  server:
    image: esphome/esphome:2024.8.0@sha256:e92f251bcd61df72b7364c4433b7ab33e22abdc448952cac550cad4c302c4fbf
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure