manifestVersion: 1
id: esphome
category: automation
name: ESPHome
version: "2024.8.0"
tagline: Intelligently manage all your ESP8266/ESP32 devices
description: >-
  ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
developer: ESPHome
website: https://esphome.io
dependencies: []
repo: https://github.com/esphome/esphome
support: https://community.home-assistant.io/c/esphome
port: 6052
gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
path: ""
defaultUsername: ""
defaultPassword: ""
torOnly: false
releaseNotes: >-
  🔔 Reminder that ESPHome on Umbrel can now automatically find devices on your local network, thanks to a switch to host network mode.


  ⚠️ As usual, please check that your configurations are still working correctly after updating.


  This release includes the following improvements:
    - Added support for new components including M5Angle8 input device, APDS9306 ambient light sensor, and LYWSD02MMC Xiaomi device
    - Implemented new features like update.perform action and update.is_available condition
    - Improved support for various existing components and platforms
    - Added runtime online image support
    - Enhanced MQTT functionality with extended device info


  Full release notes can be found at https://github.com/esphome/esphome/releases.
submitter: ShonP40
submission: https://github.com/getumbrel/umbrel-apps/pull/43